apiVersion: v1
kind: Service
metadata:
  labels:
    run: fl2k8s
  name: fl2k8s
spec:
  type: NodePort
  ports:
  - name: app
    port: 8080
    targetPort: 5010
    protocol: TCP
  selector:
    run: fl2k8s
