apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: fl8
  name: fl8
spec:
  replicas: 3
  selector:
    matchLabels:
      run: fl8
  template:
    metadata:
      labels:
        run: fl8
    spec:
      containers:
      - image: meridth/fl8
        name: fl8
        ports:
        - containerPort: 5010
          protocol: TCP
