# APP DEPLOYMENT

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: fl8
  name: fl8
spec:
  replicas: 2
  selector:
    matchLabels:
      run: fl8
  template:
    metadata:
      labels:
        run: fl8
    spec:
      containers:
      - image: jmeridth/fl8
        name: fl8
        ports:
        - containerPort: 5010
          protocol: TCP

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: fl8
  name: fl8
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5010
  selector:
    run: fl8
  type: NodePort
